# -*- coding: utf-8 -*-
"""Linear Regression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1D_Gvf3ZF-CVMsMNasdmvjZqZE08sDHaW
"""

import pandas as pd
import numpy as np
import random as rdm
x=rdm.sample(range(10),10)
y=rdm.sample(range(10),10)
df=pd.DataFrame({'X':x, 'Y':y})
df

xm=df['X'].mean()
ym=df['Y'].mean()

df['X-Xm']=df['X']-xm
df['Y-Ym']=df['Y']-ym
df

df['(X-Xm)(Y-Ym)']=df['X-Xm']* df['Y-Ym']
df

df['(X-Xm)^2']=df['X-Xm']**2

m=df["(X-Xm)(Y-Ym)"].sum()/df["(X-Xm)^2"].sum()
m

c=ym-m*xm

df['Yp']=m*df['X']+c
df

df['Eres']=(df['Y']-df['Yp'])**2
df['Ereg']=(df['Yp']-df['Y'])**2

SSreg=df['Ereg'].sum()
SSres=df['Eres'].sum()
SStotal=SSreg+SSres
R_square=SSreg/SStotal
R_square